### ISSUE TITLE
Do you think about https://github.com/SysCV/sam-hq.git ?

### ISSUE THREAD

**Issue by XinyueZ** [Jumpat/SegmentAnythingin3D#11]

**Comment by Jumpat** [comment]
Such integration is very easy since they follow the original SAM pipeline to produce segmentation results. We have already integrated a similar project (i.e., MobileSAM) into SA3D. It is possible for us to add the support to SAM-hq in the future update. But if you want to integrate it by yourself, please check the [sam3d.py](https://github.com/Jumpat/SegmentAnythingin3D/blob/main/lib/sam3d.py) for more details.
